### ISSUE TITLE
License conflicts with other major Rust packages

### ISSUE THREAD

**Issue by AustinHellerRepo** [Luthaf/time-graph#2]
Please consider updating the license from BSD-3 to Apache/MIT. This removes the need to perpetuate BSD-3 in our projects in addition to Apache/MIT while covering the same licensing scope/role.

**Comment by Luthaf** [comment]
done in 543f75beee31a843331728daa296a156d402b82e!

**Comment by Luthaf** [comment]
And released as version 0.3.0
